/* Generated By:JavaCC: Do not edit this line. ETExpressionParserConstants.java */
package com.snippetexample.flamessdk;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ETExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int BETWEEN = 8;
  /** RegularExpression Id. */
  int IN = 9;
  /** RegularExpression Id. */
  int IS = 10;
  /** RegularExpression Id. */
  int LIKE = 11;
  /** RegularExpression Id. */
  int NULL = 12;
  /** RegularExpression Id. */
  int UNQUOTED_STRING = 13;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_STRING = 14;
  /** RegularExpression Id. */
  int DOUBLE_QUOTED_STRING = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"between\"",
    "\"in\"",
    "\"is\"",
    "\"like\"",
    "\"null\"",
    "<UNQUOTED_STRING>",
    "<SINGLE_QUOTED_STRING>",
    "<DOUBLE_QUOTED_STRING>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\",\"",
  };

}
